config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    get 'chats' => 'chats#index'
    post "chats/:room_id/chats" => 'chats#create'
    post "railschatrooms" => 'railschatrooms#create'
  end

  root 'railschatrooms#index'

  get 'railschatrooms/show'

  get 'railschatrooms/new'

  get 'chats/index'

  get "/sign_in" => "sessions#new", as: :sign_in

  post "/sign_in" => 'sessions#create'

  post "/sign_out" => 'sessions#delete', as: :sign_out

  get "/users/new" => 'users#new', as: :sign_up

 post "/users" => 'users#create', as: :users

end

app/models/chat.rb
class Chat < ActiveRecord::Base
  belongs_to :user
  belongs_to :railschatroom

 validates :text, presence: true

end

app/models/railschatroom.rb
class Railschatroom < ActiveRecord::Base
  has_many :users
  has_many :chats

  validates :name, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :chats

  def full_name
      [last_name, first_name].join(", ")
    end

  validates :user_name, presence: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true
  validates :password, presence: true


end

app/controllers/api/chats_controller.rb
class Api::ChatsController < ApplicationController

  #  before_action :authenticate_user!

  before_action do
    request.format = :json
  end

  def index
    @all_users = User.all
    @chats_db = Chat.all.order("posted_at desc").limit(100)
  end

  def create

    # puts '*-*-*'*111
    # puts params

    @newchat = Chat.new params.require(:chat).permit(:text)
    # set room
    @newchat.railschatroom_id = params[:room_id]
    @newchat.user_id = @current_user.id
    @newchat.posted_at = Time.now

   #  @theroom = Railschatroom.find_by(params[:id])

   #  @theroom.chats << @newchat

    # set user
    # @message.user = User.all.sample
    # if we had auth working
   #  @chats_db.user << @current_user

    # puts '*-*-*'*111
    # pp @newchat
    # pp @message

    if @newchat.save
      render status: 201, json: @newchat
    else
      render status: 422, json: @newchat.errors
    end
  end
end

app/controllers/api/railschatrooms_controller.rb
class Api::RailschatroomsController < ApplicationController

  before_action do
     request.format = :json
   end

  def index
    @railschatrooms = Railschatroom.all


    render json: {railsChatRooms: @railschatrooms}
 end

 def create
   @railschatroom = Railschatroom.new params.require(:railschatroom).permit(:name)
   if @railschatroom.save

     render status: 201, json: @railschatroom
   else
     render status: 442, json: @railschatroom.errors
   end


 end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action do
      @current_user = User.find_by id: session[:user_id]
    end

    def authenticate_user!
      if @current_user.blank?
        redirect_to sign_in_path, notice: "Please Sign In"
      end

    end

    def sign_in user
      session[:user_id] = user.id
    end

    def sign_out
      session.delete :user_id
    end

    def user_signed_in?
      @current_user.present?
    end
    helper_method :user_signed_in?


end

app/controllers/chats_controller.rb
class ChatsController < ApplicationController

 # before_action :authenticate_user!

  def index
    
  end
end

app/controllers/railschatrooms_controller.rb
class RailschatroomsController < ApplicationController

  before_action :authenticate_user!


  def index
    @users = User.where("id != ?", @current_user.id)
    @railsrooms = Railschatroom.all
  end

  def show
  end

  def new
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create

       email = params[:email]
       password = params[:password]
       user = User.find_by email: email
       if user.present? && user.authenticate(password)
         sign_in user
         redirect_to root_path
       else
         flash.now[:alert] =  "Something is wrong with your email or password. Try gain."
         render :new
       end

     end

     def delete
       sign_out
       redirect_to root_path, notice: "You are now signed out. Thank you come again"
     end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
       @user = User.new
     end

     def create
       @user = User.new params.require(:user).permit(:user_name, :first_name, :last_name, :email, :password, :password_confirmation)
       if @user.save
         sign_in @user
         redirect_to root_path, notice: "Welcome to Railschatroom, #{@user.user_name}"
       else
         render :new
       end
     end


end

app/helpers/api/chats_helper.rb
module Api::ChatsHelper
end

app/helpers/api/railschatrooms_helper.rb
module Api::RailschatroomsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatrooms_helper.rb
module ChatroomsHelper
end

app/helpers/chats_helper.rb
module ChatsHelper
end

app/helpers/railschatrooms_helper.rb
module RailschatroomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/chatrooms/index.html.erb
<h1>Chatrooms#index</h1>
<p>Find me in app/views/chatrooms/index.html.erb</p>

app/views/chatrooms/new.html.erb
<h1>Chatrooms#new</h1>
<p>Find me in app/views/chatrooms/new.html.erb</p>

app/views/chatrooms/show.html.erb
<h1>Chatrooms#show</h1>
<p>Find me in app/views/chatrooms/show.html.erb</p>

app/views/chats/index.html.erb
<h1>Chats#index</h1>
<p>Find me in app/views/chats/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chatroom</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="page-header">
   <h1>Railschatroom <small>Share you thought...</small></h1>

   <% if user_signed_in? %>
          <div class="signin"><%= link_to 'Sign Out', sign_out_path, method: :post %></div>
          <% end %>


 </div>

 <% if alert %>
    <div class="alert alert-danger"><%= alert %></div>
  <% end %>

  <% if notice %>
    <div class="alert alert-info"><%= notice %></div>
  <% end %>




<%= yield %>


</body>
</html>

app/views/railschatrooms/index.html.erb
<h3 class="Welcome"> Welcome <%= @current_user.user_name %> </h3>

<%= react_component "Railschatroom", props={users: @users, rooms: @railsrooms}%>

app/views/railschatrooms/new.html.erb
<h1>Railschatrooms#new</h1>
<p>Find me in app/views/railschatrooms/new.html.erb</p>

app/views/railschatrooms/show.html.erb
<h1>Railschatrooms#show</h1>
<p>Find me in app/views/railschatrooms/show.html.erb</p>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<div class="col-md-6 col-md-offset-3">

<%= simple_form_for @user do |f| %>
 <%= f.input :user_name %>
 <%= f.input :first_name %>
 <%= f.input :last_name %>
 <%= f.input :email %>
 <%= f.input :password %>
 <%= f.input :password_confirmation, label: "Password Confirmation" %>
 <%= f.submit "Sign Up", class: "btn btn-primary btn-block btn-lg" %>
<% end %>

</div>